[package]
name = "ddtrace"
version = "0.0.1"
edition = "2021"

[features]
axum = ["dep:axum", "dep:axum-tracing-opentelemetry"]

[dependencies]
axum = { version = "^0.6.10", optional = true }
axum-tracing-opentelemetry = { version = "^0.10.0", optional = true }
chrono = "^0.4.24"
opentelemetry = { version = "^0.18.0", features = ["rt-tokio"] }
opentelemetry-datadog = "^0.6.0"
opentelemetry-otlp = { version = "^0.11.0" }
serde = { version = "^1.0.156", features = ["derive"] }
serde_json = "^1.0.95"
tracing = "^0.1.37"
tracing-opentelemetry = "^0.18.0"
tracing-serde = "^0.1.3"
tracing-subscriber = { version = "^0.3.16", features = ["env-filter", "json"] }
