name: Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install protobuf
        uses: taiki-e/install-action@v2
        with:
          tool: protoc
      - name: Build
        run: cargo build --verbose
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -Dclippy::all
      - name: Run tests
        run: cargo test --verbose